### PR TITLE
Fix label display for overlay timer image configuration option

### LINKED ISSUE #137: Fix label display for overlay timer image configuration option
## Bug Description

In the hydrate reminder configuration options, the timer overlay display image drop-down selector does not have a label so the user has no indication of what the drop-down options are for.

## Steps to Reproduce

1. Open the configuration options for the hydrate reminder plugin
2. See under the Timer Overlay Display options that the image drop-down menu does not have a label

## Expected Behavior

There should be a label for the overlay image drop-down menu (similar to `Text Color` and `Timer Display` seen in the screenshot below). In the code, the label is currently set to `Timer Image` but shorter labels such as `Image` or `Icon` are acceptable.

## Screenshots

config

## Environment

Operating System: Manjaro Linux x86_64
RuneLite Version: 1.8.24.3

## Additional Context

A solution to fix this issue is to shorten the length of long image names so that the drop-down does not take up the entire width of the configuration panel. Names should be shortened in a way such that they are still accurate in describing the images they represent. 

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by macslowiak**
## Associated Issue
Closes #137 

## Implemented Solution
As confirmed with @jmakhack instead of cutting names of timer images which can be difficult to understand for user I added additional config item which is only displaying title.

## Testing Details
Checked in game. No unit tests needed.
Operating System: Windows 11
RuneLite Version: 1.9.0

## Screenshots
image

### CODE REVIEW

File: src/main/java/com/hydratereminder/HydrateReminderConfig.java [hunk 1]
```diff
@@ -235,6 +242,24 @@ default Color hydrateReminderOverlayTimerTextColor()
...
+	 * </p>
+	 */
+	@ConfigItem(
+			keyName = "hydrateReminderOverlayTimerImage",
+			name = "Timer Image",
+			description = "Sets the background image of the timer display",
+			position = 3,
+			section = hydrateReminderTimerSection
+	)
+	default void overlayTimerImageTitle(){
```
Comment (mslowiak) [inline src/main/java/com/hydratereminder/HydrateReminderConfig.java:256]: `(){` -> `() {`

**Review by mslowiak — APPROVED** [review]

**Review by jmakhack — APPROVED** [review]
