### PR TITLE
Prev command with no last hydration break. 

### LINKED ISSUE #82: Prev command should not display time when no hydration breaks have been taken yet
## Bug Description

When initially logging in and running the `::hydrate prev` command before any hydration breaks have been triggered, the command will display a time since the last hydration break. Since no hydration breaks have been taken yet, it should display a separate message instead.

## Steps to Reproduce

1. Login to OSRS via RuneLite client
2. Before any hydrate reminder intervals have passed, type `::hydrate prev` in the chatbox
3. Observe that `x minutes y seconds since last hydration break.` is displayed despite never having taken a hydration break

## Expected Behavior

The `::hydrate prev` command should display a special message in this circumstance such as `No hydration breaks have been taken yet.`

## Screenshots

Screen Shot 2021-07-27 at 6 21 58 PM

## Environment

Operating System: macOS Big Sur
RuneLite Version: 1.7.16

### PR DESCRIPTION
**Pull request by medkhabt**
## Associated Issue

Closes #82 

## Implemented Solution
I seperated some of : https://github.com/jmakhack/hydrate-reminder/blob/408b3604bc616281194330046c1806f65b8eee56/src/main/java/com/hydratereminder/HydrateReminderPlugin.java#L292 responsabilites to two other method, so i can test each functionality separately. 

The two methods are: 
 - `protected Optional<Duration> getDurationSinceLastBreak(Optional<Instant> lastHydrateInstant)`
  this one calculate the duration between last break and current time, if there is no LastHydrateInstant it returns an `Optional.empty()`
- `protected String formatHandleHydratePrevCommand(Optional<Duration> timeSinceLastBreak)` this one format the 
final message after calculating the duration, if the duration is of value `Optional.empty()` it returns `No hydration breaks have been taken yet.`

I also change `lastHydrateInstant` from `Instant` to `Optional<Instant>` so it can be empty as in case of no last hydration instant. 

I added a new field `loginInstant` which is going to take Instant of user logging. If the user reset the hydrate Reminder 
the `loginInstant` is reset too. 

## Testing Details
Added 3 unitTests: 
- test `getDurationSinceLastBreak` if there is no last break than return an empty Duration Optional
- test `formatHandleHydratePrevCommand `with a duration and without a duration (Optional.empty())
- the 4th test is commented out, as i need the Clock field to test it. 

I had some difficulties testing `getDurationSinceLastBreak` when there is a break, since we use `Instant.now()` inside 
that function and if i want to test it i need to add a Clock to the instantiation of instant inside `getDurationSinceLastBreak`, so i can mock it in the test. 

I'm trying to test in rs, i launched it from HydrateReminderTest, but can't find hydrate plugin (screenshot 1) 
even tho i added it (screenshot 2). I need some help to test it in rs. 

## Screenshots
Screen Shot 2021-07-29 at 16 00 05
Screen Shot 2021-07-29 at 16 01 41

### CODE REVIEW

File: src/main/java/com/hydratereminder/HydrateReminderPlugin.java [hunk 1]
```diff
@@ -291,12 +294,37 @@ private void handleHydrateNextCommand()
...
+			return getTimeDisplay(timeSinceLastBreak.get()) + " since the last hydration break.";
+		}
+		return "No hydration breaks have been taken yet.";
+	}
+
+	/**
+	 * <p>Calculate the duration since the last break</p>
+	 * @param lastHydrateInstant Optional Instant representing the lastHydrateInstant if it exists.
+	 * @return Optional Duration representing duration from last break till now, if not it is empty.
+	 * @since 1.1.2
```
Comment (jmakhack) [inline src/main/java/com/hydratereminder/HydrateReminderPlugin.java:319]: Just a small thing, can you change all of the `@since 1.1.2` to `@since 1.2.0`?

Otherwise, all the logic looks good.
I'll test your changes tomorrow and will approve and merge this if it all runs as expected.

**Comment by jmakhack** [comment]
@medkhabt Can you also fix the code quality issues mentioned here: https://app.codacy.com/gh/jmakhack/hydrate-reminder/pullRequest?prid=7832006?

Just need to remove two unused imports in the test as well as edit an assert statement.

File: src/main/java/com/hydratereminder/HydrateReminderPlugin.java (hunk 1 above)
Comment (medkhabt) [reply src/main/java/com/hydratereminder/HydrateReminderPlugin.java]: Hi, the changes are done.

**Comment by jmakhack** [comment]
Screen Shot 2021-07-31 at 3 18 00 AM

@medkhabt, it looks like the prev command will always display the `No hydration breaks...` message even after hydration breaks have occurred. Looking at the code again, it looks like `lastHydrateInstant` is always set to `Optional.empty()`.

If you're having issues testing your changes in the game, try setting the `runeLiteVersion` in `build.gradle` to the latest RuneLite version indicated on runelite.net (1.7.18 as of writing this). The plugin with the latest code should be automatically installed when you run `HydrateReminderTest`.

**Comment by medkhabt** [comment]
> Screen Shot 2021-07-31 at 3 18 00 AM
> 
> @medkhabt, it looks like the prev command will always display the `No hydration breaks...` message even after hydration breaks have occurred. Looking at the code again, it looks like `lastHydrateInstant` is always set to `Optional.empty()`.
> 
> If you're having issues testing your changes in the game, try setting the `runeLiteVersion` in `build.gradle` to the latest RuneLite version indicated on runelite.net (1.7.18 as of writing this). The plugin with the latest code should be automatically installed when you run `HydrateReminderTest`.

Thanks, it worked.

**Comment by medkhabt** [comment]
@jmakhack  The problem is fixed, should i push the Runelite version change  to 1.7.18 ?

**Comment by jmakhack** [comment]
> @jmakhack The problem is fixed, should i push the Runelite version change to 1.7.18 ?

Looks like it will be changed anyway in another pull request so it's fine.

**Review by jmakhack — APPROVED** [review]

**Comment by jmakhack** [comment]
Tested it myself and works as expected. Approved and merging this in.
Good work and thanks for adding tests too!
